# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: lempira@gmail.com
author_name: David Rojas
contract_name: trust_game
deployment_language: python
ide_jetbrains: false
ide_vscode: true
preset_name: custom
project_name: bx-hive
use_github_actions: false

