import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AlgorandClient } from '@algorandfoundation/algokit-utils'
import { deployContracts, enableVariations } from '../integration/helpers/deployContracts'
import { createMockUsdc } from '../integration/helpers/operations'

const ENV_FILE = resolve(dirname(fileURLToPath(import.meta.url)), '../../.env.e2e.local')

/**
 * Playwright globalSetup: deploys Layer-1 (Registry) and Layer-2
 * (TrustExperiments) plus the TrustVariation bytecode so the dev server
 * (started after this) can spawn variations. Also mints a mock USDC ASA
 * so the USDC e2e round-trip can exercise the ASA path through the UI.
 * Writes the deployed app IDs + USDC asset id into .env.e2e.local; vite
 * picks them up via `--mode e2e`.
 *
 * Network: hard-locked to localhost via `defaultLocalNet()`. Both local dev
 * and CI run AlgoKit localnet on the runner's machine, so there is no
 * environment switch here — e2e never targets hosted environments.
 */
export default async function globalSetup() {
  const algorand = AlgorandClient.defaultLocalNet()
  const dispenser = await algorand.account.kmd.getLocalNetDispenserAccount()
  algorand.setSignerFromAccount(dispenser)

  const { registryAppId, trustExperimentsAppId, trustExperimentsClient } = await deployContracts(algorand, dispenser.addr)
  await enableVariations(algorand, dispenser.addr, trustExperimentsClient)

  // Mint mock USDC so the USDC e2e flow has a real ASA to target. The
  // dispenser is creator + reserve, so it can airdrop to USDC-flavored test
  // experimenters via the per-spec setup helper.
  const usdcAssetId = await createMockUsdc(algorand, dispenser.addr)

  writeFileSync(
    ENV_FILE,
    [
      '# Generated by tests/e2e/globalSetup.ts — do not edit by hand.',
      `VITE_REGISTRY_APP_ID=${registryAppId}`,
      `VITE_TRUST_EXPERIMENTS_APP_ID=${trustExperimentsAppId}`,
      `VITE_USDC_ASSET_ID=${usdcAssetId}`,
      '',
    ].join('\n'),
  )

  // eslint-disable-next-line no-console
  console.log(`[globalSetup] Registry=${registryAppId}, TrustExperiments=${trustExperimentsAppId}, USDC=${usdcAssetId}`)
}
