import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AlgorandClient } from '@algorandfoundation/algokit-utils'
import { deployContracts, enableVariations } from '../integration/helpers/deployContracts'

const ENV_FILE = resolve(dirname(fileURLToPath(import.meta.url)), '../../.env.e2e.local')

/**
 * Playwright globalSetup: deploys Layer-1 (Registry) and Layer-2
 * (TrustExperiments) plus the TrustVariation bytecode so the dev server
 * (started after this) can spawn variations. Writes the deployed app IDs
 * into .env.e2e.local; vite picks them up via `--mode e2e`.
 */
export default async function globalSetup() {
  const algorand = AlgorandClient.defaultLocalNet()
  const dispenser = await algorand.account.kmd.getLocalNetDispenserAccount()
  algorand.setSignerFromAccount(dispenser)

  const { registryAppId, trustExperimentsAppId, trustExperimentsClient } = await deployContracts(algorand, dispenser.addr)
  await enableVariations(algorand, dispenser.addr, trustExperimentsClient)

  writeFileSync(
    ENV_FILE,
    `# Generated by tests/e2e/globalSetup.ts — do not edit by hand.\nVITE_REGISTRY_APP_ID=${registryAppId}\nVITE_TRUST_EXPERIMENTS_APP_ID=${trustExperimentsAppId}\n`,
  )

  // eslint-disable-next-line no-console
  console.log(`[globalSetup] Registry=${registryAppId}, TrustExperiments=${trustExperimentsAppId}`)
}
